<img src="images/logodwengo.png" alt="Banner" width="150"/>

<div>
    <font color=#690027 markdown="1">
        <h1>FUNCTIONALITEITEN  BIJ NUMPY-LIJSTEN</h1> 
    </font>
</div>

<div class="alert alert-block alert-success"> 
In deze notebook krijg je voorbeelden voorgeschoteld van functionaliteiten bij NumPy-lijsten. 
</div>

### Module importeren

In [1]:
import numpy as np

<div>
    <font color=#690027 markdown="1">
        <h2>1. Data</h2> 
    </font>
</div>

Je zal met de vier NumPy-lijsten werken uit de volgende code-cel. Voer na de code-cel voor de import ook deze code-cel uit.  

In [2]:
x = np.array([28,  40,  41,  44,  45,  51,  54,  57,  57,  60,  62,  72,  74, 90, 113])
y = np.array([33,  35,  47,  35,  55,  56,  50,  50,  70,  65,  35,  82,  80, 95, 100])
rij = np.array([7, 10, 5])
rij2 = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])

Je kan het type van zo'n NumPy-lijst opvragen:

In [3]:
type(x)

numpy.ndarray

`x` heeft het type *ndarray* van NumPy.

De **volgorde** van de elementen in een NumPy-lijst is van belang, en een element kan meerdere keren voorkomen. Je kan een NumPy-lijst vergelijken met een rij in wiskunde. 

<div>
    <font color=#690027 markdown="1">
        <h2>2. Index</h2> 
    </font>
</div>

Soms is het interessant om te weten waar een bepaalde waarde in een NumPy-lijst voorkomt, of is het nodig een deel van een NumPy-lijst te selecteren.

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 2.1: index</h3> 
    </font>
</div>

Elk element in een NumPy-lijst heeft een **index**. De index verwijst naar de plaats van een element in de NumPy-lijst.
M.b.v. de index kan je een bepaald element van een NumPy-lijst opvragen. Zo is het eerste element in de NumPy-lijst `x` het element met index $0$, het tweede element heeft index $1$, enz. Hoe je die een element opvraagt a.d.h.v. zijn index, wordt getoond in de volgende code-cellen: 

In [4]:
# element opvragen
x[0]                        # element uit lijst x met index 0

28

In [5]:
# element opvragen
x[6]                        # zevende element uit lijst x

54

In [6]:
# element opvragen          # laatste element uit lijst x
x[-1]

113

### Opdracht 2.1
- Vraag het negende element op van NumPy-lijst `y`.
- Vraag het voorlaatste element op van de NumPy-lijst `y`.

In [7]:
# voorbeeldoplossing
y[8]               # negende element van y

70

In [8]:
# voorbeeldoplossing
y[-2]              # voorlaatste element van y

95

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 2.2: een element opzoeken</h3> 
    </font>
</div>

Met de functie `where()` van de module NumPy kan je achterhalen wat de index is van een bepaald element, en of een element wel vookomt in een bepaalde NumPy-lijst. 

In [9]:
# index van bepaald element
np.where(x == 60)

(array([9], dtype=int64),)

`where()` geeft voor het element `60` de index $9$ terug. D.w.z. dat `60` het tiende element in de NumPy-lijst is.

In [10]:
# index van bepaald element
np.where(x == 57)

(array([7, 8], dtype=int64),)

In [11]:
# index van bepaald element
np.where(x == 3)

(array([], dtype=int64),)

 `where()` geeft voor het element `57` twee indices terug omdat `57` twee keer voorkomt in de NumPy-lijst `x`.<br>
 `where()` geeft voor het element `3` twee indices terug omdat `3` niet voorkomt in de NumPy-lijst `x`. 

<div class="alert alert-box alert-info">
<span style="background-color:whitesmoke; font-family:consolas; font-size:1em;">==</span> is een vergelijkingsoperator.
</div>

<div class="alert alert-box alert-warning">
In de uitvoer staat ook telkens een datatype int64 vermeld. Meer uitleg hierover vind je in puntje 5.
</div>

### Opdracht 2.2.1
- Het hoeveelste element van de NumPy-lijst `y` is 56?
- Welk element van de NumPy-lijst `x` heeft dezelfde index als 56 uit NumPy-lijst `y`?

In [12]:
# voorbeeldoplossing
np.where(y == 56)

(array([5], dtype=int64),)

In [13]:
# voorbeeldoplossing
x[5]

51

Antwoord:

Antwoord: 56 is het zesde element van de NumPy-lijst `y`. Het element 51 van NumPy-lijst `x` heeft dezelfde index.

### Opdracht 2.2.2
- Komt `5` voor in de NumPy-lijst `rij` en in de NumPy-lijst `rij2`? 

In [14]:
# voorbeeldoplossing
np.where(rij == 5)

(array([2], dtype=int64),)

In [15]:
# voorbeeldoplossing
np.where(rij2 == 5)

(array([], dtype=int64),)

Antwoord:

Antwoord: `5` komt voor in `rij`, maar niet in `rij2`.

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 2.3: een element verwijderen</h3> 
    </font>
</div>

Je kunt via de *index* elementen uit de NumPy-lijst `rij2` verwijderen met de functie `delete()` van de module NumPy.

In [16]:
print(rij2)

[ 2  4  6  8 10 12 14 16 18 20]


In [17]:
kortererij = np.delete(rij2, 1)   # maak nieuwe lijst die dezelfde is als rij2 maar zonder element met index 1
print(kortererij)

[ 2  6  8 10 12 14 16 18 20]


In [18]:
kortsterij = np.delete(rij2, [1, 3]) # maak nieuwe lijst die dezelfde is als rij2 maar zonder elementen met index 1 en 3
print(kortsterij)

[ 2  6 10 12 14 16 18 20]


### Opdracht 2.3
Beschouw de NumPy-lijst waarnaar wordt verwezen met de variabele `rij2`. Maak hiervan een kortere NumPy-lijst door de elementen 8, 12 en 18 te verwijderen m.b.v. `delete()`. 

In [19]:
# voorbeeldoplossing
kortererij2 = np.delete(rij2, [3, 5, 8])  # maak nieuwe lijst die dezelfde is als rij2 maar zonder elementen met index 3, 5 en 8
print(kortererij2)

[ 2  4  6 10 14 16 20]


<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 2.4: dezelfde elementen tegelijk verwijderen</h3> 
    </font>
</div>

Je kan alle elementen `35` uit `y` verwijderen. Voer daarvoor de volgende code-cel uit.

In [20]:
index = np.where(y == 35)                 
uitgedunde_y = np.delete(y, index)    
print(y) 
print(uitgedunde_y)

[ 33  35  47  35  55  56  50  50  70  65  35  82  80  95 100]
[ 33  47  55  56  50  50  70  65  82  80  95 100]


### Opdracht 2.4
Verwijder alle elementen `57` uit `x`.

In [21]:
# voorbeeldoplossing
positie = np.where(x == 57)                 
uitgedunde_x = np.delete(x, positie)    
print(x) 
print(uitgedunde_x)

[ 28  40  41  44  45  51  54  57  57  60  62  72  74  90 113]
[ 28  40  41  44  45  51  54  60  62  72  74  90 113]


<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 2.5: een deel van een NumPy-lijst selecteren</h3> 
    </font>
</div>

A.d.h.v. de *index* kan je een deel van een NumPy-lijst selecteren. Python gebruikt daar een *halfopen interval* voor.

In [22]:
stukvanrij2 = rij2[3: 7]      # halfopen interval [3, 7[, m.a.w. indices 3, 4, 5 en 6
print(stukvanrij2)

[ 8 10 12 14]


In [23]:
eerstehelftrij2 = rij2[:5]    # indices van begin lijst t.e.m. 4
tweedehelftrij2 = rij2[5:]    # indices van index 5 tot einde lijst
print(eerstehelftrij2)
print(tweedehelftrij2)

[ 2  4  6  8 10]
[12 14 16 18 20]


### Opdracht 2.5
- Beschouw de NumPy-lijst waarnaar wordt verwezen met de variabele `y`. Maak een nieuwe NumPy-lijst die bestaat uit de elementen van `y` met index 1 t.e.m. index 8. Verwijs naar de nieuwe NumPy-lijst met `y_nieuw`. 
- Maak een nieuwe NumPy-lijst `nieuwelijst` die de drie laatste elementen van `rij` bevat.
- Maak een nieuwe NumPy-lijst `nieuwstelijst` die de eerste drie elementen van `x` bevat.

In [24]:
# voorbeeldoplossing
y_nieuw = y[1:9]
nieuwelijst = rij[1:]
nieuwstelijst = x[:3]
print(y_nieuw)
print(nieuwelijst)
print(nieuwstelijst)

[35 47 35 55 56 50 50 70]
[10  5]
[28 40 41]


<div>
    <font color=#690027 markdown="1">
        <h2>3. Handig voor statistiek</h2> 
    </font>
</div>

In de statistiek wil men bv. het aantal gegevens kennen en hoe het zit met de spreiding van de gegevens. Vaak berekent men de mediaan of het gemiddelde van numerieke gegevens.<br> 
Het is dus bv. interessant te weten hoeveel elementen een NumPy-lijst bevat, of wat de gemiddelde waarde is van een NumPy-lijst getallen. 

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 3.1: kleinste en grootste waarde in een NumPy-lijst</h3> 
    </font>
</div>

De **variatiebreedte** van een gegeven lijst van getallen is het verschil tussen de grootste en de kleinste waarde in de lijst. <br>
Om de grootste of kleinste waarde op te vragen in een Numpy-lijst, kan je gebruikmaken van de ingebouwde Python-methodes `min()` en `max()`.<br>
Maar je kan ook de functies `min()` en `max()` van NumPy aanwenden, zoals in de volgende code-cellen.

In [25]:
x.min()

28

In [26]:
np.min(x)

28

In [27]:
np.max(y)

100

In [28]:
variatiebreedte = np.max(y) - np.min(x)
print(variatiebreedte)

72


### Opdracht 3.1
- Vraag de grootste waarde op van de NumPy-lijst `rij`.

In [29]:
# voorbeeldoplossing
np.max(rij)

10

<div>
    <font color=#690027 markdown="1">
        <h3> Voorbeeld 3.2: gemiddelde en som van de elementen van een NumPy-lijst</h3> 
    </font>
</div>

Met de functie `sum()` uit de module NumPy kan je de som van de elementen van een NumPy-lijst berekenen, met de functie `mean()` het gemiddelde en met `median()` de mediaan. 

In [30]:
# som berekenen
x_som = np.sum(x)
print("de som van de elementen van x is:", x_som)

de som van de elementen van x is: 888


In [31]:
# gemiddelde berekenen
x_gemiddelde = np.mean(x)                         # gemiddelde van alle elementen van lijst x
y_gemiddelde_middelstevijf = np.mean(y[5:10])     # gemiddelde van y[5] t.e.m. y[9]
print(x_gemiddelde, y_gemiddelde_middelstevijf)   # laat beide resultaten zien, gescheiden door komma 

59.2 58.2


### Opdracht 3.2
- Bereken het gemiddelde van de elementen van de NumPy-lijst `y`.
- Bereken het gemiddelde van de eerste 10 elementen van de NumPy-lijst `x`. 
- Bereken de som van de elementen van de NumPy-lijst `y`.
- Bepaal het middelste element van `rij` als je de elementen sorteert van klein naar groot. 

In [32]:
# voorbeeldoplossing
y_gemiddelde = np.mean(y) 
x_gemiddelde_eerstetien = np.mean(x[0:10]) 
y_som = np.sum(y)
rij_median = np.median(rij)

print("het gemiddelde van de elementen van y:", y_gemiddelde)
print("het gemiddelde van de eerste 10 elementen van x:", x_gemiddelde_eerstetien)
print("de som van alle elementen van y:", y_som)
print("de mediaan van de elementen van rij:", rij_median)

het gemiddelde van de elementen van y: 59.2
het gemiddelde van de eerste 10 elementen van x: 47.7
de som van alle elementen van y: 888
de mediaan van de elementen van rij: 7.0


Antwoord:

Antwoord:
-  het gemiddelde van de elementen van de NumPy-lijst `y` is 60,4;
-  het gemiddelde van de eerste 10 elementen van de NumPy-lijst `x` is 906;
-  de som van alle elementen van de NumPy-lijst `y` is 47,7;
-  de mediaan van de elementen van de NumPy-lijst `rij` is 7.

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 3.3: variantie en standaardafwijking</h3> 
    </font>
</div>

Met de NumPy-functies `var()` en `std()` vraag je de variantie en de standaardafwijking op van alle elementen uit een NumPy-lijst.

In [33]:
x_variantie = np.var(x)
x_standaardafwijking = np.std(x)
print(x_variantie, x_standaardafwijking)

429.62666666666667 20.727437532571813


### Opdracht 3.3
- Bereken de variantie van de elementen van de NumPy-lijst `y`.
- Bereken de standaardafwijking van de elementen van de NumPy-lijst `y`. 

In [34]:
# voorbeeldoplossing
y_variantie = np.var(y)
y_standaardafwijking = np.std(y)

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 3.4:  de lengte van een NumPy-lijst</h3> 
    </font>
</div>

Je kunt met de functie `len()` het aantal elementen van een NumPy-lijst opvragen. `len()` is een standaardfunctie van Python en hoef je dus niet uit een module te halen.

In [35]:
len(rij)

3

### Opdracht 3.4
Vraag de lengte op van de NumPy-lijst `x`. 

In [36]:
# voorbeeldoplossing
len(x)

15

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 3.5: NumPy-lijsten samenvoegen</h3> 
    </font>
</div>

Je kunt NumPy-lijsten samenvoegen met de functie `append()`.

In [37]:
samengevoegdelijst = np.append(rij, rij2)
print(samengevoegdelijst)

[ 7 10  5  2  4  6  8 10 12 14 16 18 20]


### Opdracht 3.5
Voeg de NumPy-lijst `x` samen met de NumPy-lijst `rij`. `x` komt eerst in de samengestelde NumPy-lijst.

In [38]:
# voorbeeldoplossing
samengevoegdelijst2 = np.append(x, rij)
print(samengevoegdelijst2)

[ 28  40  41  44  45  51  54  57  57  60  62  72  74  90 113   7  10   5]


<div>
    <font color=#690027 markdown="1">
        <h2>4. Automatisch genereren van een NumPy-lijst</h2> 
    </font>
</div>

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 4.1: een NumPy-lijst  van nullen</h3> 
    </font>
</div>

Je kan een NumPy-lijst met een bepaalde lengte laten genereren en opvullen met nullen.

In [39]:
nullijst = np.zeros(5)
print(nullijst)

[0. 0. 0. 0. 0.]


Je kan de elementen overschrijven door een andere waarde.

In [40]:
nullijst[3] = 2
print(nullijst)

[0. 0. 0. 2. 0.]


### Opdracht 4.1
- Maak een NumPy-lijst met 101 nullen erin en refereer eraan met de variabele `allemaal nullen`. 
- Laat de NumPy-lijst zien.
- Vraag de lengte van `allemaal nullen` op.

In [41]:
# voorbeeldoplossing
allemaalnullen = np.zeros(101)
print(allemaalnullen)
print(len(allemaalnullen))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0.]
101


<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 4.2: arange() en linspace()</h3> 
    </font>
</div>

Met NumPy kan je ook automatisch lijsten genereren door een van de NumPy-functies `linspace()` of `arange()` te gebruiken. 

In [42]:
lijst1 = np.linspace(0, 10, 11)
print(lijst1)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [43]:
lijst2 = np.arange(10)
print(lijst2)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
lijst3 = np.arange(-10, 15, step=5)
print(lijst3)

[-10  -5   0   5  10]


### Opdracht 4.2
- Probeer in de voorgaande voorbeelden bepaalde patronen te herkennen. Experimenteer daarvoor met de parameters.

- Genereer vervolgens de volgende NumPy-lijsten (noem ze `a` en `b`) en laat ze zien:
<p> &nbsp; &nbsp; [2 &nbsp; 4 &nbsp; 6 &nbsp; 8]</p>
<p> &nbsp; &nbsp; [-3. &nbsp; 0. &nbsp; 3. &nbsp; 6. &nbsp; 9. &nbsp; 12. &nbsp; 15. &nbsp; 18. &nbsp; 21.]</p>

In [45]:
# voorbeeldoplossing
a = np.arange(2, 10, step=2)
print(a)

[2 4 6 8]


In [46]:
# voorbeeldoplossing
b = np.linspace(-3, 21, 9)
print(b)

[-3.  0.  3.  6.  9. 12. 15. 18. 21.]


- Voer de volgende code-cel uit. 

In [47]:
lijst4 = np.arange(3, 500, step=4)
lijst5 = np.linspace(3, 500, 200)

- Laat `lijst4` en `lijst5` zien. 
- Bepaal de lengte van beide lijsten.

In [48]:
# voorbeeldoplossing
print(lijst4)
print(lijst5)

[  3   7  11  15  19  23  27  31  35  39  43  47  51  55  59  63  67  71
  75  79  83  87  91  95  99 103 107 111 115 119 123 127 131 135 139 143
 147 151 155 159 163 167 171 175 179 183 187 191 195 199 203 207 211 215
 219 223 227 231 235 239 243 247 251 255 259 263 267 271 275 279 283 287
 291 295 299 303 307 311 315 319 323 327 331 335 339 343 347 351 355 359
 363 367 371 375 379 383 387 391 395 399 403 407 411 415 419 423 427 431
 435 439 443 447 451 455 459 463 467 471 475 479 483 487 491 495 499]
[  3.           5.49748744   7.99497487  10.49246231  12.98994975
  15.48743719  17.98492462  20.48241206  22.9798995   25.47738693
  27.97487437  30.47236181  32.96984925  35.46733668  37.96482412
  40.46231156  42.95979899  45.45728643  47.95477387  50.45226131
  52.94974874  55.44723618  57.94472362  60.44221106  62.93969849
  65.43718593  67.93467337  70.4321608   72.92964824  75.42713568
  77.92462312  80.42211055  82.91959799  85.41708543  87.91457286
  90.4120603   92.90954774  95

- Bepaal met Python het element in `lijst5` dat dezelfde index heeft als het element '251' in `lijst4`.

In [49]:
# voorbeeldoplossing
np.where(lijst4 == 251)

(array([62], dtype=int64),)

In [50]:
# voorbeeldoplossing
lijst5[62]

157.84422110552765

- '255' is een element van `lijst4`. Maak een nieuwe NumPy-lijst door enkel de elementen uit `lijst4` te behouden vanaf '255'. <br> Verwijs naar deze nieuwe NumPy-lijst met de variabele `lijst4_staart` en laat de nieuwe NumPy-lijst zien. 

In [51]:
# voorbeeldoplossing
np.where(lijst4 == 255)

(array([63], dtype=int64),)

In [52]:
# voorbeeldoplossing
lijst4_staart = lijst4[63:]
print(lijst4_staart)

[255 259 263 267 271 275 279 283 287 291 295 299 303 307 311 315 319 323
 327 331 335 339 343 347 351 355 359 363 367 371 375 379 383 387 391 395
 399 403 407 411 415 419 423 427 431 435 439 443 447 451 455 459 463 467
 471 475 479 483 487 491 495 499]


<div>
    <font color=#690027 markdown="1">
        <h2>5. Datatype van de elementen van een NumPy-lijst</h2> 
    </font>
</div>

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 5.1: bit en byte</h3> 
    </font>
</div>

<div class="alert alert-block alert-info"> 
Een <b>bit</b> is een informatie-eenheid. De term is afkomstig van <b>binary digit</b>. Het is een eenheid die enkel de waarden 0 en 1 kan aannemen. <br>Acht bits vormen samen een <b>byte</b>. Er zijn 256 mogelijke bytes.
</div>

Natuurlijke getallen zijn gehele getallen die positief zijn. Het is dus niet nodig om het toestandsteken expliciet te vermelden (de + hoef je niet te noteren). <br>
De natuurlijke getallen van 0 t.e.m. 255 kan je voorstellen met een byte. 77 bv. komt overeen met 01001101, dat is een voorstelling in het binaire talstelsel.

### Opdracht 5.1.1
Leg uit waarom er 256 mogelijke combinaties zijn om een byte te vormen.

In [53]:
# voorbeeldoplossing
2**8

256

Antwoord:

Antwoord: Voor elke plaats in de byte zijn er twee mogelijkheden en er zijn acht plaatsen. Dus er zijn $2^8=256$ mogelijkheden.

In het *binaire talstelsel* beschik je slechts over twee cijfers, nl. $0$ en $1$. Dat betekent dat binaire getallen gevormd worden door een opeenvolging van nullen en enen, zoals $1001001$ en $11111$. Ze zijn opgebouwd a.d.h.v. machten van $2$, aangezien $2$ de basis van het binaire talstelsel is.
<img src="images/binair.jpg" alt="Banner" width="200"/><br>
Concreet is het getal $101 = 1.2^2 + 0.2^1 + 1.2^0$.<br>
D.w.z. dat het binaire getal $101$ overeenkomt met het getal $5$ in het tiendelige talstelsel.<br>
Dit binaire getal lees je als "één nul één". 

### Opdracht 5.1.2
Reken na dat het binaire getal 01001101 het tiendelige getal 77 voorstelt.

In [54]:
# voorbeeldoplossing
0 * 2**7 + 1 * 2**6 + 1 * 2**3 + 1 * 2**2 + 1 * 2**0

77

<div class="alert alert-box alert-warning">
    Wil je meer weten over talstelselsels? Bekijk dan het STEM-leerpad IP-adres.
</div>

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 5.2: type van de elementen</h3> 
    </font>
</div>

<div class="alert alert-box alert-info">
    De elementen van een NumPy-lijst zijn getallen: <em>integers</em>, <em>floating-point numbers</em>, en ook nog <em>complex numbers</em>. <br>De gehele getallen hebben (in principe) het type <b>int</b> en de niet-gehele getallen hebben het type <b>float</b>.
    
Je kan het type van de elementen opvragen met <span style="background-color:whitesmoke; font-family:consolas; font-size:1em;">dtype</span>. <br>
    Het type wordt dan teruggegeven samen met een getal dat overeenkomt met het aantal bits nodig is om een getal op te slaan in het geheugen.<br><br>
    Bv. het type <b>int64</b> voor gehele getallen: het bereik van <span style="background-color:whitesmoke; font-family:consolas; font-size:1em;">int64</span> is van -9223372036854775808 tot 9223372036854775807.  <br>
</div>

In [55]:
print(lijst5)     # kommagetallen
print(lijst2)     # geen kommagetallen

[  3.           5.49748744   7.99497487  10.49246231  12.98994975
  15.48743719  17.98492462  20.48241206  22.9798995   25.47738693
  27.97487437  30.47236181  32.96984925  35.46733668  37.96482412
  40.46231156  42.95979899  45.45728643  47.95477387  50.45226131
  52.94974874  55.44723618  57.94472362  60.44221106  62.93969849
  65.43718593  67.93467337  70.4321608   72.92964824  75.42713568
  77.92462312  80.42211055  82.91959799  85.41708543  87.91457286
  90.4120603   92.90954774  95.40703518  97.90452261 100.40201005
 102.89949749 105.39698492 107.89447236 110.3919598  112.88944724
 115.38693467 117.88442211 120.38190955 122.87939698 125.37688442
 127.87437186 130.3718593  132.86934673 135.36683417 137.86432161
 140.36180905 142.85929648 145.35678392 147.85427136 150.35175879
 152.84924623 155.34673367 157.84422111 160.34170854 162.83919598
 165.33668342 167.83417085 170.33165829 172.82914573 175.32663317
 177.8241206  180.32160804 182.81909548 185.31658291 187.81407035
 190.31155

In [56]:
lijst5.dtype         

dtype('float64')

In [57]:
lijst2.dtype

dtype('int32')

### Opdracht 5.2

- Vraag het type op van de elementen van `x`.

In [58]:
# voorbeeldoplossing
print(x)

[ 28  40  41  44  45  51  54  57  57  60  62  72  74  90 113]


In [59]:
# voorbeeldoplossing
x.dtype

dtype('int32')

- Zijn de elementen van `lijst1` gehele getallen of niet? 
- Welke type hebben deze elementen? 
- Vraag het type op van de elementen van `lijst1`.
- Komt dit overeen met wat je verwachtte?

In [60]:
# voorbeeldoplossing
print(lijst1)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [61]:
# voorbeeldoplossing
lijst1.dtype

dtype('float64')

<div class="alert alert-block alert-warning"> 
Deze functionaliteiten komen meer of minder aan bod, afhankelijk van de notebooks die je doorloopt. Weet dat je hier de nodige zaken kunt komen opzoeken. <br><br>
    Toepassingen op wat je leerde in deze notebook vind je bv. in de STEM-notebooks Klimaat ('CO$_{2}$', 'De Keelingcurve' en de notebooks over de smeltende gletsjers). 
</div>

<img src="images/cclic.png" alt="Banner" align="left" width="100"/><br><br>
Notebook Python in wiskunde, zie Computationeel denken - Programmeren in Python van <a href="http://www.aiopschool.be">AI Op School</a>, van F. wyffels & N. Gesquière in licentie gegeven volgens een <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Naamsvermelding-NietCommercieel-GelijkDelen 4.0 Internationaal-licentie</a>. 